-- VBC Analytics Semantic View — with lab additions
-- Adds PATIENT_INCOME_BAND + ENCOUNTER_MONTH/YEAR dimensions and 5 VBC metrics
-- to the Autopilot-generated baseline. Run this script in your snowday workspace.
-- CREATE OR ALTER is idempotent: updates in place if the view already exists.

create or alter semantic view VBC_LAB.CARE_ANALYTICS.VBC_ANALYTICS_SV
	tables (
		SYNTHEA.SILVER.CONDITIONS comment='The table contains records of medical conditions diagnosed for patients. Each record represents a single condition instance, capturing the condition''s coded classification, associated patient and encounter, the duration of the condition, and the city of the synthetic patient.',
		SYNTHEA.SILVER.ENCOUNTERS primary key (ENCOUNTER_ID) comment='The table contains records of patient medical encounters, capturing details about individual healthcare visits or interactions. Each record includes information about the involved parties (patient, provider, organization, and payer), the nature and classification of the encounter, associated costs and insurance coverage, and the reason for the visit.',
		SYNTHEA.SILVER.MEDICATIONS comment='The table contains records of medication prescriptions associated with patient encounters. Each record represents a single medication course and includes details about the medication itself, associated costs and payer coverage, the reason for prescribing, and the geographic location of the patient.',
		SYNTHEA.SILVER.OBSERVATIONS comment='The table contains records of clinical observations captured during patient encounters. Each record represents a single observation and includes details about the patient, the associated encounter, and the nature of the observation such as its category, coded description, measured value, and units of measurement.',
		SYNTHEA.SILVER.PATIENTS primary key (PATIENT_ID) comment='The table contains records of individual patients, including personal identifying information and demographic details. Each record represents a single patient and covers attributes such as biographical dates, identity documents, name components, and demographic characteristics including marital status, race, ethnicity, gender, and geographic information.',
		SYNTHEA.SILVER.PAYERS primary key (PAYER_ID) comment='The table contains records of health insurance payers, including their contact and location details. Each record represents a single payer and includes financial summaries such as revenue, covered and uncovered amounts, and utilization metrics across encounters, medications, procedures, and immunizations, as well as customer counts and average quality of life scores.',
		SYNTHEA.SILVER.PROCEDURES comment='The table contains records of medical procedures performed on patients. Each record represents a single procedure and includes details about the associated patient and encounter, the procedure type and description, cost information, and the reason for the procedure, scoped to a specific city.',
		SYNTHEA.SILVER.PROVIDERS primary key (PROVIDER_ID) comment='The table contains records of healthcare providers and their associated attributes. Each record represents an individual provider and includes details about their identity, demographics, medical speciality, geographic location, and affiliated organization, along with aggregate counts of encounters and procedures.'
	)
	relationships (
		CONDITIONS_TO_ENCOUNTERS as CONDITIONS(ENCOUNTER_ID) references ENCOUNTERS(ENCOUNTER_ID),
		CONDITIONS_TO_PATIENTS as CONDITIONS(PATIENT_ID) references PATIENTS(PATIENT_ID),
		ENCOUNTERS_TO_PATIENTS as ENCOUNTERS(PATIENT_ID) references PATIENTS(PATIENT_ID),
		ENCOUNTERS_TO_PAYERS as ENCOUNTERS(PAYER_ID) references PAYERS(PAYER_ID),
		ENCOUNTERS_TO_PROVIDERS as ENCOUNTERS(PROVIDER_ID) references PROVIDERS(PROVIDER_ID),
		MEDICATIONS_TO_ENCOUNTERS as MEDICATIONS(ENCOUNTER_ID) references ENCOUNTERS(ENCOUNTER_ID),
		MEDICATIONS_TO_PATIENTS as MEDICATIONS(PATIENT_ID) references PATIENTS(PATIENT_ID),
		MEDICATIONS_TO_PAYERS as MEDICATIONS(PAYER_ID) references PAYERS(PAYER_ID),
		OBSERVATIONS_TO_ENCOUNTERS as OBSERVATIONS(ENCOUNTER_ID) references ENCOUNTERS(ENCOUNTER_ID),
		OBSERVATIONS_TO_PATIENTS as OBSERVATIONS(PATIENT_ID) references PATIENTS(PATIENT_ID),
		PROCEDURES_TO_ENCOUNTERS as PROCEDURES(ENCOUNTER_ID) references ENCOUNTERS(ENCOUNTER_ID),
		PROCEDURES_TO_PATIENTS as PROCEDURES(PATIENT_ID) references PATIENTS(PATIENT_ID)
	)
	facts (
		ENCOUNTERS.BASE_ENCOUNTER_COST as BASE_ENCOUNTER_COST comment='The base cost of the encounter, not including any line item costs related to medications, immunizations, procedures, or other services.' sample_values ('183.23', '69.38', '112.97'),
		ENCOUNTERS.PAYER_COVERAGE as PAYER_COVERAGE comment='The amount of cost covered by the Payer.' sample_values ('731.68', '3436.72', '759.42'),
		ENCOUNTERS.TOTAL_CLAIM_COST as TOTAL_CLAIM_COST comment='The total cost of the encounter, including all line items.' sample_values ('41309.94', '2738.36', '904.92'),
		MEDICATIONS.BASE_COST as BASE_COST comment='The line item cost of the medication.' sample_values ('1.47', '0.73', '0.99'),
		MEDICATIONS.PAYER_COVERAGE as PAYER_COVERAGE comment='The amount covered or reimbursed by the Payer.' sample_values ('408.20', '64.62', '183.46'),
		MEDICATIONS.TOTALCOST as TOTALCOST comment='The total cost of the prescription, including all dispenses.' sample_values ('1.11', '8386.56', '7.68'),
		PATIENTS.HEALTHCARE_COVERAGE as HEALTHCARE_COVERAGE comment='The total lifetime cost of healthcare services that were covered by Payers (i.e. what the insurance company paid).' sample_values ('803376.48', '599541.28', '673725.25'),
		PATIENTS.HEALTHCARE_EXPENSES as HEALTHCARE_EXPENSES comment='The total lifetime cost of healthcare to the patient (i.e. what the patient paid).' sample_values ('38010.04', '14409.81', '1422104.61'),
		PATIENTS.LAT as LAT comment='Latitude of Patient address.' sample_values ('40.436537891992480', '40.464558951571960', '40.470892304824260'),
		PATIENTS.LON as LON comment='Longitude of Patient address.' sample_values ('-87.58418148560617', '-87.59906561377016', '-87.75167330498918'),
		PAYERS.AMOUNT_COVERED as AMOUNT_COVERED comment='The monetary amount paid to Organizations during the entire simulation.' sample_values ('396788738.40', '23970274422.24', '2050104327.31'),
		PAYERS.AMOUNT_UNCOVERED as AMOUNT_UNCOVERED comment='The monetary amount not paid to Organizations during the entire simulation, and covered out of pocket by patients.' sample_values ('2840318033.55', '72640882.24', '1743702849.19'),
		PAYERS.QOLS_AVG as QOLS_AVG comment='The average Quality of Life Scores (QOLS) for all patients enrolled with this Payer during the entire simulation.' sample_values ('0.90799848608661420', '0.85600658044812520', '0.93837731612506100'),
		PAYERS.REVENUE as REVENUE comment='The monetary revenue of the Payer during the entire simulation.' sample_values ('2718479175.30', '144143118.53', '93451732.97'),
		PROCEDURES.BASE_COST as BASE_COST comment='The line item cost of the procedure.' sample_values ('398.63', '6857.81', '434.05'),
		PROVIDERS.LAT as LAT comment='Latitude of Provider address.' sample_values ('41.520484800000000', '42.329843000000000', '42.281043200000000'),
		PROVIDERS.LON as LON comment='Longitude of Provider address.' sample_values ('-81.49950460000000', '-81.58649390000000', '-81.57577590000000')
	)
	dimensions (
		CONDITIONS._SYSTEM as "SYSTEM" comment='Coding system for the code' sample_values ('http://snomed.info/sct', 'SNOMED-CT'),
		CONDITIONS.CODE as CODE comment='Diagnosis code from SNOMED-CT' sample_values ('278588009', '266934004', '161744009'),
		CONDITIONS.CONDITION_ID as CONDITION_ID comment='CONDITIONS primary key' sample_values ('1001639', '1011952', '1004384'),
		CONDITIONS.DESCRIPTION as DESCRIPTION comment='Description of the condition.' sample_values ('Facial laceration', 'Preeclampsia', 'Idiopathic atrophic hypothyroidism (disorder)'),
		CONDITIONS.ENCOUNTER_ID as ENCOUNTER_ID comment='Foreign key to Primary key in Encounters table' sample_values ('32162737', '61134156', '32119054'),
		CONDITIONS.PATIENT_ID as PATIENT_ID comment='Foreign key to primary key in Patietns table.' sample_values ('1562014', '1561862', '1687728'),
		CONDITIONS.SYNTHEA_CITY as SYNTHEA_CITY comment='City generated by Synthea.' sample_values ('PITTSBURGH', 'AUSTIN', 'BOSTON'),
		CONDITIONS.CONDITION_START as CONDITION_START comment='The date the condition was diagnosed.' sample_values ('2013-08-25', '1946-02-17', '2024-10-09'),
		CONDITIONS.CONDITION_STOP as CONDITION_STOP comment='The date the condition resolved, if applicable.' sample_values ('2005-12-06', '2022-02-06', '1990-11-26'),
		ENCOUNTERS.CODE as CODE comment='Encounter code from SNOMED-CT.' sample_values ('394701000', '439708006', '50849002'),
		ENCOUNTERS.DESCRIPTION as DESCRIPTION comment='Description of the type of encounter.' sample_values ('Hospital admission (procedure)', 'Administration of vaccine to produce active immunity (procedure)', 'Outpatient procedure'),
		ENCOUNTERS.ENCOUNTER_ID as ENCOUNTER_ID comment='Primary key for table Encounters.' sample_values ('64338156', '57222869', '30346807'),
		ENCOUNTERS.ENCOUNTERCLASS as ENCOUNTERCLASS comment='The class of the encounter, such as ambulatory, emergency, inpatient, wellness, or urgentcare.' sample_values ('urgentcare', 'ambulatory', 'virtual'),
		-- ADDED: expression dimensions for time-based analysis
		ENCOUNTERS.ENCOUNTER_MONTH as DATE_TRUNC('MONTH', ENCOUNTER_START) comment='Month of encounter',
		ENCOUNTERS.ENCOUNTER_YEAR as YEAR(ENCOUNTER_START) comment='Year of encounter',
		ENCOUNTERS.ORGANIZATION_ID as ORGANIZATION_ID comment='Foreign key to primary key in Organizations table.' sample_values ('1001307', '1002705', '1002715'),
		ENCOUNTERS.PATIENT_ID as PATIENT_ID comment='Foreign key to primary key in Patietns table.' sample_values ('1257836', '2352804', '1332205'),
		ENCOUNTERS.PAYER_ID as PAYER_ID comment='Foreign key to primary key in Payers table.' sample_values ('1000075', '1000071', '1000058'),
		ENCOUNTERS.PROVIDER_ID as PROVIDER_ID comment='Foreign key to primary key in Providers table.' sample_values ('3057620', '3057956', '3060472'),
		ENCOUNTERS.REASONCODE as REASONCODE comment='Diagnosis code from SNOMED-CT, only if this encounter targeted a specific condition.' sample_values ('72892002', '444814009'),
		ENCOUNTERS.REASONDESCRIPTION as REASONDESCRIPTION comment='Description of the reason code.' sample_values ('Fracture of clavicle', 'Gout', 'Loss of teeth (disorder)'),
		ENCOUNTERS.SYNTHEA_CITY as SYNTHEA_CITY comment='City generated by Synthea.' sample_values ('DETROIT', 'CHICAGO', 'MIAMI'),
		ENCOUNTERS.ENCOUNTER_START as ENCOUNTER_START comment='The date and time the encounter started.' sample_values ('2014-05-03T10:45:20.000Z', '1997-11-07T15:43:52.000Z', '2006-12-31T01:14:36.000Z'),
		ENCOUNTERS.ENCOUNTER_STOP as ENCOUNTER_STOP comment='The date and time the encounter concluded.' sample_values ('2008-11-30T08:05:44.000Z', '2022-06-24T08:15:08.000Z', '2020-08-13T13:23:07.000Z'),
		MEDICATIONS.CODE as CODE comment='Medication code from RxNorm.' sample_values ('1361048', '106892', '617310'),
		MEDICATIONS.DESCRIPTION as DESCRIPTION comment='Description of the medication.' sample_values ('Vitamin B12 5 MG/ML Injectable Solution', 'budesonide 0.25 MG/ML Inhalation Suspension', 'zidovudine 300 MG Oral Tablet'),
		MEDICATIONS.DISPENSES as DISPENSES comment='The number of times the prescription was filled.' sample_values ('156', '1', '4'),
		MEDICATIONS.ENCOUNTER_ID as ENCOUNTER_ID comment='Primary key for table Encounters.' sample_values ('48350202', '47704552', '57265181'),
		MEDICATIONS.MEDICATION_ID as MEDICATION_ID comment='MEDICATIONS primary key' sample_values ('33916019', '33916156', '33811282'),
		MEDICATIONS.PATIENT_ID as PATIENT_ID comment='Foreign key to primary key in Patients table.' sample_values ('1101676', '1698226', '2414261'),
		MEDICATIONS.PAYER_ID as PAYER_ID comment='Foreign key to primary key in Payers table.' sample_values ('1000076', '1000002', '1000007'),
		MEDICATIONS.REASONCODE as REASONCODE comment='Diagnosis code from SNOMED-CT specifying why this medication was prescribed.' sample_values ('10509002', '45816000', '67811000119102'),
		MEDICATIONS.REASONDESCRIPTION as REASONDESCRIPTION comment='Description of the reason code.' sample_values ('Hyperlipidemia (disorder)', 'Anemia (disorder)'),
		MEDICATIONS.SYNTHEA_CITY as SYNTHEA_CITY comment='City generated by Synthea.' sample_values ('CLEVELAND', 'MIAMI', 'SAN FRANCISCO'),
		MEDICATIONS.MED_START as MED_START comment='The date and time the medication was prescribed.' sample_values ('2023-02-23T01:49:13.000Z', '1971-06-05T17:59:37.000Z', '2024-02-29T08:15:34.000Z'),
		MEDICATIONS.MED_STOP as MED_STOP comment='The date and time the prescription ended, if applicable.' sample_values ('2022-08-02T10:55:29.000Z', '2010-09-16T13:46:56.000Z', '2020-09-15T15:31:14.000Z'),
		OBSERVATIONS._TYPE as "TYPE" comment='The datatype of Value: text or numeric' sample_values ('numeric', 'n'),
		OBSERVATIONS.CATEGORY as CATEGORY comment='Observation category.' sample_values ('laboratory', 'social-history', 'survey'),
		OBSERVATIONS.CODE as CODE comment='Observation or Lab code from LOINC' sample_values ('QALY', '72514-3', '8302-2'),
		OBSERVATIONS.DESCRIPTION as DESCRIPTION comment='Description of the observation or lab.' sample_values ('Has lack of transportation kept you from medical appointments  meetings  work  or from getting things needed for daily living', 'MCH [Entitic mass] by Automated count', 'Platelets [#/volume] in Blood by Automated count'),
		OBSERVATIONS.ENCOUNTER_ID as ENCOUNTER_ID comment='Primary key for table Encounters.' sample_values ('51387011', '7020231', '63759902'),
		OBSERVATIONS.OBSERVATION_ID as OBSERVATION_ID comment='OBSERVATIONS primary key' sample_values ('391752298', '123132740', '391752219'),
		OBSERVATIONS.PATIENT_ID as PATIENT_ID comment='Foreign key to primary key in Patietns table.' sample_values ('1367823', '2010149', '2010154'),
		OBSERVATIONS.SYNTHEA_CITY as SYNTHEA_CITY comment='City generated by Synthea.' sample_values ('DETROIT', 'TAMPA', 'BOSTON'),
		OBSERVATIONS.UNITS as UNITS comment='The units of measure for the value.' sample_values ('{nominal}', 'mg/dL'),
		OBSERVATIONS.VALUE as VALUE comment='The recorded value of the observation.' sample_values ('3.1', '119.0', 'No'),
		OBSERVATIONS.OBSERVATION_DATE as OBSERVATION_DATE comment='The date and time the observation was performed.' sample_values ('2004-04-13T03:56:03.000Z', '1994-08-17T00:08:24.000Z', '2018-06-10T20:23:38.000Z'),
		PATIENTS.ADDRESS as ADDRESS comment='Patient street address without commas or newlines.' sample_values ('353 Turner Corner Suite 45', '100 Kerluke Crossroad', '211 Walter Arcade Suite 26'),
		PATIENTS.BIRTHPLACE as BIRTHPLACE comment='Name of the town where the patient was born.' sample_values ('Washington  District of Columbia  US', 'Cantho  Cần Thơ  VN', 'Juarez  Chihuahua  MX'),
		PATIENTS.CITY as CITY comment='Patient address city.' sample_values ('Cleveland', 'Boston', 'Nashville'),
		PATIENTS.COUNTY as COUNTY comment='Patient address county.' sample_values ('Hillsborough County', 'Miami-Dade County', 'Davidson County'),
		PATIENTS.DRIVERS as DRIVERS comment='Patient Drivers License identifier.' sample_values ('S99940149', 'S99914096', 'S99928370'),
		PATIENTS.ETHNICITY as ETHNICITY comment='Description of the patient primary ethnicity.' sample_values ('nonhispanic', 'hispanic'),
		PATIENTS.FIPS as FIPS comment='Patient FIPS county code.' sample_values ('42003', '26163', '12057'),
		PATIENTS.FIRST as FIRST comment='First name of the patient.' sample_values ('Laquanda', 'Darcel', 'Chong'),
		PATIENTS.GENDER as GENDER comment='Gender. M is male, F is female.' sample_values ('M', 'F'),
		PATIENTS.INCOME as INCOME comment='Annual income for the Patient' sample_values ('15585', '51628', '113432'),
		PATIENTS.LAST as LAST comment='Last or surname of the patient.' sample_values ('Farías', 'Saavedra', 'Bechtelar'),
		PATIENTS.MAIDEN as MAIDEN comment='Maiden name of the patient.' sample_values ('Kuhlman', 'Ramos', 'Ponce'),
		PATIENTS.MARITAL as MARITAL comment='Marital Status. M is married, S is single. Currently no support for divorce (D) or widowing (W)' sample_values ('M', 'S', 'W'),
		PATIENTS.MIDDLE as MIDDLE comment='Middle name of the patient.' sample_values ('Grazyna', 'Cyrus', 'Megan'),
		PATIENTS.PASSPORT as PASSPORT comment='Patient Passport identifier.' sample_values ('X81175090X', 'X84098667X', 'X82179671X'),
		PATIENTS.PATIENT_ID as PATIENT_ID comment='Primary key for PATIENTS table.' sample_values ('1664916', '1008856', '1008735'),
		PATIENTS.PREFIX as PREFIX comment='Name prefix, such as Mr., Mrs., Dr., etc.' sample_values ('Mrs.', 'Mr.', 'Ms.'),
		PATIENTS.RACE as RACE comment='Description of the patient primary race.' sample_values ('asian', 'white', 'native'),
		PATIENTS.SSN as SSN comment='Patient Social Security identifier.' sample_values ('999-46-4912', '999-92-5546', '999-51-4306'),
		PATIENTS.STATE as STATE comment='Patient address state.' sample_values ('District of Columbia', 'Texas', 'Illinois'),
		PATIENTS.SUFFIX as SUFFIX comment='Name suffix, such as PhD, MD, JD, etc.' sample_values ('PhD', 'JD'),
		PATIENTS.SYNTHEA_CITY as SYNTHEA_CITY comment='City generated by Synthea.' sample_values ('PITTSBURGH', 'SALT LAKE CITY', 'CLEVELAND'),
		PATIENTS.ZIP as ZIP comment='Patient zip code.' sample_values ('15207', '33603', '60640'),
		PATIENTS.BIRTHDATE as BIRTHDATE comment='The date the patient was born.' sample_values ('1969-06-11', '2006-02-13', '1970-01-28'),
		PATIENTS.DEATHDATE as DEATHDATE comment='The date the patient died.' sample_values ('1990-02-10', '2018-02-21', '1991-07-02'),
		-- ADDED: expression dimension bucketing annual income into bands
		PATIENTS.PATIENT_INCOME_BAND as CASE WHEN INCOME < 30000 THEN '<30k' WHEN INCOME >= 30000 AND INCOME < 60000 THEN '30-60k' WHEN INCOME >= 60000 AND INCOME < 100000 THEN '60-100k' WHEN INCOME >= 100000 THEN '100k+' ELSE 'Unknown' END comment='Patient income band categorization',
		PAYERS.ADDRESS as ADDRESS comment='Payer street address without commas or newlines.',
		PAYERS.CITY as CITY comment='Street address city.',
		PAYERS.COVERED_ENCOUNTERS as COVERED_ENCOUNTERS comment='The number of Encounters paid for by this Payer.' sample_values ('226678', '1528389', '37187314'),
		PAYERS.COVERED_IMMUNIZATIONS as COVERED_IMMUNIZATIONS comment='The number of Immunizations paid for by this Payer.' sample_values ('177420', '727359', '11589261'),
		PAYERS.COVERED_MEDICATIONS as COVERED_MEDICATIONS comment='The number of Medications paid for by this Payer.' sample_values ('19665387', '10734473', '15676029'),
		PAYERS.COVERED_PROCEDURES as COVERED_PROCEDURES comment='The number of Procedures paid for by this Payer.' sample_values ('25668470', '765553', '444422'),
		PAYERS.MEMBER_MONTHS as MEMBER_MONTHS comment='The total number of months that patients were enrolled with this Payer during the simulation and paid monthly premiums (if any).' sample_values ('108916092', '5287344', '2945796'),
		PAYERS.NAME as NAME comment='Name of the Payer.' sample_values ('Medicare', 'Medicaid', 'Dual Eligible'),
		PAYERS.PAYER_ID as PAYER_ID comment='Primary key for PAYERS table.' sample_values ('1000001', '1000034', '1000068'),
		PAYERS.PHONE as PHONE comment='Payer phone number.',
		PAYERS.STATE_HEADQUARTERED as STATE_HEADQUARTERED comment='Street address state abbreviation.',
		PAYERS.SYNTHEA_CITY as SYNTHEA_CITY comment='City generated by Synthea.' sample_values ('AUSTIN', 'BOSTON', 'CHICAGO'),
		PAYERS.UNCOVERED_ENCOUNTERS as UNCOVERED_ENCOUNTERS comment='The number of Encounters not paid for by this Payer, and paid out of pocket by patients.' sample_values ('0', '4544829', '2482316'),
		PAYERS.UNCOVERED_IMMUNIZATIONS as UNCOVERED_IMMUNIZATIONS comment='The number of Immunizations not paid for by this Payer, and paid out of pocket by patients.' sample_values ('1581686', '4694416', '0'),
		PAYERS.UNCOVERED_MEDICATIONS as UNCOVERED_MEDICATIONS comment='The number of Medications not paid for by this Payer, and paid out of pocket by patients.' sample_values ('2076169', '0', '10070328'),
		PAYERS.UNCOVERED_PROCEDURES as UNCOVERED_PROCEDURES comment='The number of Procedures not paid for by this Payer, and paid out of pocket by patients.' sample_values ('37562172', '5406616', '9882160'),
		PAYERS.UNIQUE_CUSTOMERS as UNIQUE_CUSTOMERS comment='The number of unique patients enrolled with this Payer during the simulation.' sample_values ('24492', '23593', '2034'),
		PAYERS.ZIP as ZIP comment='Street address zip or postal code.',
		PROCEDURES.CODE as CODE comment='Procedure code from SNOMED-CT' sample_values ('430193006', '447759004', '281789004'),
		PROCEDURES.DESCRIPTION as DESCRIPTION comment='Description of the procedure.' sample_values ('Take blood sample', 'Dental X-ray bitewing (procedure)', 'Manual pelvic examination (procedure)'),
		PROCEDURES.ENCOUNTER_ID as ENCOUNTER_ID comment='Primary key for table Encounters.' sample_values ('42461525', '42143143', '17467043'),
		PROCEDURES.PATIENT_ID as PATIENT_ID comment='Foreign key to primary key in Patietns table.' sample_values ('1586698', '1998794', '1586721'),
		PROCEDURES.PROCEDURE_ID as PROCEDURE_ID comment='PROCEDURES primary key' sample_values ('118208231', '118208429', '30345854'),
		PROCEDURES.REASONCODE as REASONCODE comment='The medical reason or diagnosis code associated with why a procedure was performed.' sample_values ('46177005', '431857002', '65966004'),
		PROCEDURES.REASONDESCRIPTION as REASONDESCRIPTION comment='Description of the reason code.' sample_values ('Gingivitis (disorder)', 'Sleep disorder (disorder)', 'Laceration of thigh'),
		PROCEDURES.SYNTHEA_CITY as SYNTHEA_CITY comment='City generated by Synthea.' sample_values ('SAN FRANCISCO', 'BOSTON', 'CHICAGO'),
		PROCEDURES.PROC_START as PROC_START comment='The date and time the procedure was performed.' sample_values ('2020-04-19T05:18:13.000Z', '2021-08-09T13:26:04.000Z', '2022-09-14T19:21:46.000Z'),
		PROCEDURES.PROC_STOP as PROC_STOP comment='The date and time the procedure was completed, if applicable.' sample_values ('2023-01-28T09:14:06.000Z', '2005-12-20T00:15:12.000Z', '2023-02-05T22:40:59.000Z'),
		PROVIDERS.ADDRESS as ADDRESS comment='Provider street address without commas or newlines.' sample_values ('5001 MAYFIELD RD  SUITE 105', '19530 BAGLEY RD', '12300 MCCRACKEN ROAD'),
		PROVIDERS.CITY as CITY comment='Street address city.' sample_values ('MAYFIELD HTS', 'BEACHWOOD', 'MIDDLEBURG HEIGHTS'),
		PROVIDERS.ENCOUNTERS as ENCOUNTERS comment='The number of Encounters performed by this provider.' sample_values ('307734', '2578', '1555'),
		PROVIDERS.GENDER as GENDER comment='Gender. M is male, F is female.' sample_values ('F', 'M'),
		PROVIDERS.NAME as NAME comment='First and last name of the Provider.' sample_values ('Lena Schowalter', 'Sun Kulas', 'Twyla Marquardt'),
		PROVIDERS.ORGANIZATION_ID as ORGANIZATION_ID comment='Foreign key to primary key in ORGANIZATIONS table.' sample_values ('1000362', '1000317', '1000202'),
		PROVIDERS.PROCEDURES as PROCEDURES comment='The number of Procedures performed by this provider.' sample_values ('0'),
		PROVIDERS.PROVIDER_ID as PROVIDER_ID comment='Primary key for PROVIDERS table' sample_values ('3057357', '3057301', '3057307'),
		PROVIDERS.SPECIALITY as SPECIALITY comment='Provider speciality.' sample_values ('GENERAL PRACTICE'),
		PROVIDERS.STATE as STATE comment='Street address state abbreviation.' sample_values ('MA', 'OH', 'TX'),
		PROVIDERS.SYNTHEA_CITY as SYNTHEA_CITY comment='City generated by Synthea.' sample_values ('BOSTON', 'CLEVELAND', 'AUSTIN'),
		PROVIDERS.ZIP as ZIP comment='Street address zip or postal code.' sample_values ('441091900', '441182571', '440671086')
	)
	-- ADDED: VBC metrics
	metrics (
		ENCOUNTERS.TOTAL_COST_OF_CARE as SUM(TOTAL_CLAIM_COST) comment='Total cost of care across all encounters',
		ENCOUNTERS.PAYER_COVERAGE_RATE as DIV0(SUM(PAYER_COVERAGE), SUM(TOTAL_CLAIM_COST)) comment='Payer coverage rate',
		ENCOUNTERS.AVG_COST_PER_ENCOUNTER as AVG(TOTAL_CLAIM_COST) comment='Average cost per encounter',
		ENCOUNTERS.TOTAL_ENCOUNTER_COUNT as COUNT(ENCOUNTER_ID) comment='Total count of encounters',
		ENCOUNTERS.AVOIDABLE_ED_RATE as DIV0(SUM(CASE WHEN ENCOUNTERCLASS = 'emergency' AND REASONCODE IN ('59621000','15777000','195662009','10509002','444814009','40055000','271737000','427898007','195967001','233604007','82423001','431855005','431856006','162864005') THEN 1 ELSE 0 END), COUNT(ENCOUNTER_ID)) comment='Rate of avoidable ED visits for ambulatory-sensitive conditions relative to total encounters'
	)
	with extension (CA='{"tables":[{"name":"CONDITIONS","dimensions":[{"name":"_SYSTEM"},{"name":"CODE"},{"name":"CONDITION_ID"},{"name":"DESCRIPTION"},{"name":"ENCOUNTER_ID"},{"name":"PATIENT_ID"},{"name":"SYNTHEA_CITY"}],"time_dimensions":[{"name":"CONDITION_START"},{"name":"CONDITION_STOP"}]},{"name":"ENCOUNTERS","dimensions":[{"name":"CODE"},{"name":"DESCRIPTION"},{"name":"ENCOUNTER_ID"},{"name":"ENCOUNTERCLASS"},{"name":"ORGANIZATION_ID"},{"name":"PATIENT_ID"},{"name":"PAYER_ID"},{"name":"PROVIDER_ID"},{"name":"REASONCODE"},{"name":"REASONDESCRIPTION"},{"name":"SYNTHEA_CITY"},{"name":"ENCOUNTER_YEAR"}],"facts":[{"name":"BASE_ENCOUNTER_COST"},{"name":"PAYER_COVERAGE"},{"name":"TOTAL_CLAIM_COST"}],"time_dimensions":[{"name":"ENCOUNTER_START"},{"name":"ENCOUNTER_STOP"},{"name":"ENCOUNTER_MONTH"}],"metrics":[{"name":"TOTAL_COST_OF_CARE"},{"name":"PAYER_COVERAGE_RATE"},{"name":"AVG_COST_PER_ENCOUNTER"},{"name":"TOTAL_ENCOUNTER_COUNT"},{"name":"AVOIDABLE_ED_RATE"}]},{"name":"MEDICATIONS","dimensions":[{"name":"CODE"},{"name":"DESCRIPTION"},{"name":"DISPENSES"},{"name":"ENCOUNTER_ID"},{"name":"MEDICATION_ID"},{"name":"PATIENT_ID"},{"name":"PAYER_ID"},{"name":"REASONCODE"},{"name":"REASONDESCRIPTION"},{"name":"SYNTHEA_CITY"}],"facts":[{"name":"BASE_COST"},{"name":"PAYER_COVERAGE"},{"name":"TOTALCOST"}],"time_dimensions":[{"name":"MED_START"},{"name":"MED_STOP"}]},{"name":"OBSERVATIONS","dimensions":[{"name":"_TYPE"},{"name":"CATEGORY"},{"name":"CODE"},{"name":"DESCRIPTION"},{"name":"ENCOUNTER_ID"},{"name":"OBSERVATION_ID"},{"name":"PATIENT_ID"},{"name":"SYNTHEA_CITY"},{"name":"UNITS"},{"name":"VALUE"}],"time_dimensions":[{"name":"OBSERVATION_DATE"}]},{"name":"PATIENTS","dimensions":[{"name":"ADDRESS"},{"name":"BIRTHPLACE"},{"name":"CITY"},{"name":"COUNTY"},{"name":"DRIVERS"},{"name":"ETHNICITY"},{"name":"FIPS"},{"name":"FIRST"},{"name":"GENDER"},{"name":"INCOME"},{"name":"LAST"},{"name":"MAIDEN"},{"name":"MARITAL"},{"name":"MIDDLE"},{"name":"PASSPORT"},{"name":"PATIENT_ID"},{"name":"PREFIX"},{"name":"RACE"},{"name":"SSN"},{"name":"STATE"},{"name":"SUFFIX"},{"name":"SYNTHEA_CITY"},{"name":"ZIP"},{"name":"PATIENT_INCOME_BAND"}],"facts":[{"name":"HEALTHCARE_COVERAGE"},{"name":"HEALTHCARE_EXPENSES"},{"name":"LAT"},{"name":"LON"}],"time_dimensions":[{"name":"BIRTHDATE"},{"name":"DEATHDATE"}]},{"name":"PAYERS","dimensions":[{"name":"ADDRESS"},{"name":"CITY"},{"name":"COVERED_ENCOUNTERS"},{"name":"COVERED_IMMUNIZATIONS"},{"name":"COVERED_MEDICATIONS"},{"name":"COVERED_PROCEDURES"},{"name":"MEMBER_MONTHS"},{"name":"NAME"},{"name":"PAYER_ID"},{"name":"PHONE"},{"name":"STATE_HEADQUARTERED"},{"name":"SYNTHEA_CITY"},{"name":"UNCOVERED_ENCOUNTERS"},{"name":"UNCOVERED_IMMUNIZATIONS"},{"name":"UNCOVERED_MEDICATIONS"},{"name":"UNCOVERED_PROCEDURES"},{"name":"UNIQUE_CUSTOMERS"},{"name":"ZIP"}],"facts":[{"name":"AMOUNT_COVERED"},{"name":"AMOUNT_UNCOVERED"},{"name":"QOLS_AVG"},{"name":"REVENUE"}]},{"name":"PROCEDURES","dimensions":[{"name":"CODE"},{"name":"DESCRIPTION"},{"name":"ENCOUNTER_ID"},{"name":"PATIENT_ID"},{"name":"PROCEDURE_ID"},{"name":"REASONCODE"},{"name":"REASONDESCRIPTION"},{"name":"SYNTHEA_CITY"}],"facts":[{"name":"BASE_COST"}],"time_dimensions":[{"name":"PROC_START"},{"name":"PROC_STOP"}]},{"name":"PROVIDERS","dimensions":[{"name":"ADDRESS"},{"name":"CITY"},{"name":"ENCOUNTERS"},{"name":"GENDER"},{"name":"NAME"},{"name":"ORGANIZATION_ID"},{"name":"PROCEDURES"},{"name":"PROVIDER_ID"},{"name":"SPECIALITY"},{"name":"STATE"},{"name":"SYNTHEA_CITY"},{"name":"ZIP"}],"facts":[{"name":"LAT"},{"name":"LON"}]}],"relationships":[{"name":"CONDITIONS_TO_ENCOUNTERS","join_type":"inner"},{"name":"CONDITIONS_TO_PATIENTS","join_type":"inner"},{"name":"ENCOUNTERS_TO_PATIENTS","join_type":"inner"},{"name":"ENCOUNTERS_TO_PAYERS","join_type":"inner"},{"name":"ENCOUNTERS_TO_PROVIDERS","join_type":"inner"},{"name":"MEDICATIONS_TO_ENCOUNTERS","join_type":"inner"},{"name":"MEDICATIONS_TO_PATIENTS","join_type":"inner"},{"name":"MEDICATIONS_TO_PAYERS","join_type":"inner"},{"name":"OBSERVATIONS_TO_ENCOUNTERS","join_type":"inner"},{"name":"OBSERVATIONS_TO_PATIENTS","join_type":"inner"},{"name":"PROCEDURES_TO_ENCOUNTERS","join_type":"inner"},{"name":"PROCEDURES_TO_PATIENTS","join_type":"inner"}]}');
